### ISSUE TITLE
How to switch from home robot to turtle 3?

### ISSUE THREAD

**Issue by jeonhuhuhu** [notmahi/clip-fields#11]
Hi

Since CLIP-Field results in 3D coordinates, 
if we only experiment with navigation using the coordinates of the detected object, can we connect to Turtle 3 instead of Home-Robot? 

If we were to conduct an experiment with Turtle 3, what information could we refer to for testing? 

And for navigation, could you share information on how to connect with Turtle 3?

Could you share how to sequentially connect the Turtle 3 robots?

Thank you in advance for your valuable answer.

**Comment by notmahi** [comment]
Hi @jeonhuhuhu , I am glad to know that you're trying to connect this to a robot. However, we have never worked with a turtlebot, and wouldn't know how to connect to one either.

The ok-robot repo might have more relevant information since there the integration with a Stretch robot is published: https://github.com/ok-robot/ok-robot.

Closing this issue since it's out of scope.
